-- ============================================================================
--  Lamoia Audit System - Supabase Schema
--  Run this in the Supabase SQL Editor (https://app.supabase.com) on your project.
--  Compatible with the Next.js app — same column names as the spec.
-- ============================================================================

-- ============================================================================
-- USERS
-- ============================================================================
create table if not exists public."Users" (
  id_user bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "Login" text unique,
  "Senha" text,
  "Tipo" text,
  "Nome" text,
  "Status" text,
  constraint Users_pkey primary key (id_user)
);

comment on column public."Users"."Tipo" is 'Allowed login tipos: Admin Senior, Admin Junior, Comercial. Others (Qualidade, User, etc.) are NOT authorized.';
comment on column public."Users"."Status" is 'a = ativo, i = inativo. Only Status = a can log in.';

-- ============================================================================
-- CLIENTES
-- ============================================================================
create table if not exists public."Clientes" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  "Codigo" integer unique,
  "Razao" text,
  "CNPJ/CPF" bigint,
  "Endereco" text,
  "Bairro" text,
  "Cidade" text,
  "UF" text,
  constraint Clientes_pkey primary key (id),
  constraint Clientes_Codigo_key unique ("Codigo")
);

-- ============================================================================
-- AG_AGENDA
-- ============================================================================
create table if not exists public.ag_agenda (
  id_agenda bigint generated by default as identity not null,
  data_criacao timestamp with time zone not null default now(),
  id_gerente bigint,
  id_vendedor bigint,
  status_atual text,
  data_agenda date,
  mes_referencia text,
  placa text,
  -- ⚠️ Renamed from "hora inicial" / "hora fim" → "hora_inicial" / "hora_fim"
  --    (column types remain timestamp without time zone — app converts HH:MM ↔ Date)
  hora_inicial timestamp without time zone,
  hora_fim timestamp without time zone,
  total_hora text,
  eficiencia real,
  id_auditor double precision,
  data_aud date,
  almoco text,
  obs_geral character varying,
  constraint ag_agenda_pkey primary key (id_agenda),
  constraint ag_agenda_id_gerente_fkey foreign KEY (id_gerente) references "Users" (id_user) on update CASCADE on delete CASCADE,
  constraint ag_agenda_id_vendedor_fkey foreign KEY (id_vendedor) references "Users" (id_user) on update CASCADE on delete CASCADE
);

-- ============================================================================
-- AG_AGENDA_DIARIA
-- ============================================================================
create table if not exists public.ag_agenda_diaria (
  id_ad bigint generated by default as identity not null,
  id_a bigint,
  id_clientes integer,
  status_atendimento text,  -- 'Pendente' | 'Pendente Auditoria' | 'Em Atendimento' | 'Realizado' | 'Cancelado'
  -- ⚠️ Renamed from data_hora_atendimento to data_hora_atendimento_inicio
  -- + added data_hora_atendimento_fim
  data_hora_atendimento_inicio timestamp without time zone,
  data_hora_atendimento_fim timestamp without time zone,
  observacao text,
  latitude text,
  longitude text,
  constraint ag_agenda_diaria_pkey primary key (id_ad),
  constraint ag_agenda_diaria_id_a_fkey foreign KEY (id_a) references ag_agenda (id_agenda) on update CASCADE on delete CASCADE,
  constraint ag_agenda_diaria_id_clientes_fkey foreign KEY (id_clientes) references "Clientes" ("Codigo") on update CASCADE on delete CASCADE
);

-- ============================================================================
-- FOTOS_VIS (photos for each visita / ag_agenda_diaria row)
-- ============================================================================
create table if not exists public.fotos_vis (
  id_foto bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  id_vis bigint,
  "Nome_Foto" text,
  "Tipo" text,           -- 'Fachada' | 'Antes' | 'Depois'
  "Loc_Foto" character varying,  -- URL or path to the photo
  constraint fotos_vis_pkey primary key (id_foto),
  constraint fotos_vis_Nome_Foto_key unique ("Nome_Foto"),
  constraint fotos_vis_id_vis_fkey foreign KEY (id_vis) references ag_agenda_diaria (id_ad) on update CASCADE on delete CASCADE
);

-- ============================================================================
-- LOG_ACESSO (login history — who logged in and when)
-- ============================================================================
create table if not exists public.log_acesso (
  id_log bigint generated by default as identity not null,
  id_user bigint,
  login text,
  ip text,
  user_agent text,
  data_hora timestamp with time zone not null default now(),
  constraint log_acesso_pkey primary key (id_log),
  constraint log_acesso_id_user_fkey foreign KEY (id_user) references "Users" (id_user) on update CASCADE on delete set null
);

-- ============================================================================
-- INDEXES (recommended for production)
-- ============================================================================
create index if not exists idx_ag_agenda_data_agenda on public.ag_agenda (data_agenda);
create index if not exists idx_ag_agenda_mes_referencia on public.ag_agenda (mes_referencia);
create index if not exists idx_ag_agenda_id_gerente on public.ag_agenda (id_gerente);
create index if not exists idx_ag_agenda_id_vendedor on public.ag_agenda (id_vendedor);
create index if not exists idx_ag_agenda_status on public.ag_agenda (status_atual);
create index if not exists idx_ag_agenda_diaria_id_a on public.ag_agenda_diaria (id_a);
create index if not exists idx_ag_agenda_diaria_status on public.ag_agenda_diaria (status_atendimento);
create index if not exists idx_clientes_codigo on public."Clientes" ("Codigo");
create index if not exists idx_fotos_vis_id_vis on public.fotos_vis (id_vis);
create index if not exists idx_log_acesso_id_user on public.log_acesso (id_user);
create index if not exists idx_log_acesso_data_hora on public.log_acesso (data_hora desc);
create index if not exists idx_fotos_vis_tipo on public.fotos_vis ("Tipo");

-- ============================================================================
-- LOGIN VALIDATION FUNCTION (mirrors the spec, with robustness fixes)
-- ============================================================================
-- ⚠️ FIXES vs original spec:
--   1. Prefers users with Status='a' when multiple rows share the same Login
--      (original LIMIT 1 is non-deterministic and could return an inactive user).
--   2. Trims whitespace and compares Status case-insensitively
--      (handles 'A', 'a ', ' a' values that would fail the original `!= 'a'` check).
--   3. Returns the same generic error messages for security.
-- ============================================================================
create or replace function public.validar_login(p_login text, p_senha text)
returns json
language plpgsql
security definer
as $$
DECLARE
  user_record public."Users";
  is_valid BOOLEAN;
  v_hash_text TEXT;
  v_status_norm TEXT;
BEGIN
  -- 1. Busca o usuário pelo login. Prefere Status='a' (case-insensitive, trimmed)
  --    para evitar que LIMIT 1 retorne uma linha inativa quando houver duplicatas.
  SELECT * INTO user_record
  FROM public."Users"
  WHERE "Login" = p_login
  ORDER BY
    CASE
      WHEN trim(coalesce("Status", '')) ILIKE 'a' THEN 0
      ELSE 1
    END ASC,
    id_user ASC
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN json_build_object('sucesso', false, 'mensagem', 'Login e senha inválidos.');
  END IF;

  -- 2. Regra de Status ativo — robusta a case/whitespace
  v_status_norm := lower(trim(coalesce(user_record."Status", '')));
  IF v_status_norm != 'a' THEN
    RETURN json_build_object('sucesso', false, 'mensagem', 'Usuário inativo. Contate o administrador.');
  END IF;

  -- 3. LÓGICA DE VALIDAÇÃO DE SENHA:
  -- Primeiro verificamos se É um hash para evitar que o crypt() receba um salt inválido e retorne NULL
  IF user_record."Senha" LIKE '$2a$%' OR user_record."Senha" LIKE '$2b$%' OR user_record."Senha" LIKE '$2y$%' THEN
    v_hash_text := user_record."Senha";
    -- Ajuste de compatibilidade: PostgreSQL crypt() prefere $2a$
    IF v_hash_text LIKE '$2b$%' OR v_hash_text LIKE '$2y$%' THEN
      v_hash_text := '$2a$' || SUBSTRING(v_hash_text FROM 5);
    END IF;
    is_valid := (v_hash_text = crypt(p_senha, v_hash_text));
  ELSE
    -- Se não parece um hash, tratamos como texto puro (legado)
    is_valid := (user_record."Senha" = p_senha);
  END IF;

  IF is_valid THEN
    -- Migração silenciosa para Bcrypt $2a$ se a senha ainda estiver em texto puro
    IF user_record."Senha" NOT LIKE '$2a$%' AND user_record."Senha" NOT LIKE '$2b$%' AND user_record."Senha" NOT LIKE '$2y$%' THEN
      UPDATE public."Users"
      SET "Senha" = crypt(p_senha, gen_salt('bf', 10))
      WHERE "id_user" = user_record."id_user";
    END IF;

    -- Retorna sucesso e os dados do usuário (sem a senha!)
    RETURN json_build_object(
      'sucesso', true,
      'usuario', json_build_object(
        'id_user', user_record."id_user",
        'Nome', user_record."Nome",
        'Login', user_record."Login",
        'Tipo', user_record."Tipo",
        'Status', user_record."Status"
      )
    );
  ELSE
    -- Senha não confere
    RETURN json_build_object('sucesso', false, 'mensagem', 'Login e senha inválidos.');
  END IF;
END;
$$;

-- ============================================================================
-- DIAGNOSTIC HELPER (optional — useful to find duplicate / inactive logins)
-- ============================================================================
-- Returns one row per Login showing how many rows exist and their statuses.
-- Run this once to detect duplicates or inactive rows that may cause login failures.
--   SELECT * FROM public.diagnostic_users_por_login();
create or replace function public.diagnostic_users_por_login()
returns table (
  login text,
  total_rows bigint,
  ativos bigint,
  inativos bigint,
  status_distinct text
)
language sql
security definer
as $$
  SELECT
    "Login" AS login,
    COUNT(*) AS total_rows,
    COUNT(*) FILTER (WHERE lower(trim(coalesce("Status", ''))) = 'a') AS ativos,
    COUNT(*) FILTER (WHERE lower(trim(coalesce("Status", ''))) != 'a') AS inativos,
    string_agg(DISTINCT "Status", ', ') AS status_distinct
  FROM public."Users"
  WHERE "Login" IS NOT NULL
  GROUP BY "Login"
  ORDER BY "Login";
$$;

-- ============================================================================
-- ENABLE ROW LEVEL SECURITY (recommended for production)
-- ============================================================================
alter table public."Users" enable row level security;
alter table public."Clientes" enable row level security;
alter table public.ag_agenda enable row level security;
alter table public.ag_agenda_diaria enable row level security;

-- Service role bypasses RLS — the Next.js API uses the service role key.
-- The anon key has NO policies by default (denies all access from the client).
-- Add explicit policies below if you want to expose specific reads to anon clients.

-- ============================================================================
-- SEED ADMIN USER
-- Password: admin123 (bcrypt cost 10)
-- ============================================================================
insert into public."Users" ("Login", "Senha", "Tipo", "Nome", "Status")
values (
  'admin',
  crypt('admin123', gen_salt('bf', 10)),
  'Admin Senior',
  'Administrador Geral',
  'a'
)
on conflict ("Login") do nothing;

-- Optional sample vendedores (uncomment to use)
-- insert into public."Users" ("Login", "Senha", "Tipo", "Nome", "Status") values
--   ('comercial1', crypt('admin123', gen_salt('bf', 10)), 'Comercial', 'Carlos Santos', 'a'),
--   ('comercial2', crypt('admin123', gen_salt('bf', 10)), 'Comercial', 'Mariana Costa', 'a'),
--   ('comercial3', crypt('admin123', gen_salt('bf', 10)), 'Comercial', 'Pedro Almeida', 'a')
-- on conflict ("Login") do nothing;

-- Optional sample clientes (uncomment to use)
-- insert into public."Clientes" ("Codigo", "Razao", "Endereco", "Bairro", "Cidade", "UF") values
--   (1001, 'Supermercado Central Ltda', 'Av Brasil 1000', 'Centro', 'São Paulo', 'SP'),
--   (1002, 'Farmácia Saúde Total', 'Rua das Flores 250', 'Jardim Primavera', 'Campinas', 'SP')
-- on conflict ("Codigo") do nothing;
